import time
import random
passlist = ['qs0a11wq', 'pussyallday', 'Iluvmeloon', 'c103eedm', 'edl009az', 'lss13awq', 'ilovemesum', 'chomohomo', 'yursuchadumass', 'pw12aos0', 'ilovecock', 'plwa21ry', 'johnwikk', 'passwerd', 'wordzz', 'kittrkat', 'sodsado', 'wl1298za', 'iwmanjs1', '12pqaza9', '00wkamsl', 'scemmoi', 'rokkstar', 'epstein', 'qsp0921s', 'uz02a1lw', 'la21qpao']
print("\033[1;37;40m")
lol = input("Enter Instagram Username: ")

lol2 = input("Enter how many passwords you want to try: ")

kok = input("This will not work on your own account")
kook = input("You must be on a different network")
kkk = input("Please use responsibly")

print("[*] Loading [                      ]")
time.sleep(3)
print("")
print("[*] Loading [=====                 ]")
time.sleep(3)
print("")
time.sleep(0.3)
print("[*] Loading [===============       ]")
time.sleep(3)
print("")
time.sleep(0.3)
print("[*] Loading [======================]")
time.sleep(1)
print("\033[1;31;40m")
time.sleep(0.3)
print("Attacking "+lol+"[=                  ]")
time.sleep(0.5)
print("Attacking "+lol+"[==                 ]")
time.sleep(0.5)
print("Attacking "+lol+"[===                ]")
time.sleep(0.5)
print("Attacking "+lol+"[====               ]")
time.sleep(0.5)
print("Attacking "+lol+"[=====              ]")
time.sleep(0.5)
print("Attacking "+lol+"[======             ]")
time.sleep(0.5)
print("Attacking "+lol+"[=======            ]")
time.sleep(0.5)
print("Attacking "+lol+"[========           ]")
time.sleep(0.5)
print("Attacking "+lol+"[=========          ]")
time.sleep(0.5)
print("Attacking "+lol+"[===========        ]")
time.sleep(0.5)
print("Attacking "+lol+"[=============      ]")
time.sleep(0.5)
print("Attacking "+lol+"[===================]")
time.sleep(2)
print("PASSWORD FOUND----------------------------------------------------------")
time.sleep(1)
print("Tried " + lol2 + " passwords on " + lol)
time.sleep(1)
print("\033[1;34;40m")
print(lol+ "'s password is: ", random.choice(passlist))
print("\033[1;37;40m")
